version: "3.9"

services:
  backend:
    build: backend
    image: face-detection-backend:1.0
    ports:
      - "8080:8080"
    env_file:
      - backend/.env_backend
 
  frontend:
    build: frontend
    image: face-detection-frontend:1.0
    depends_on:
      - backend
    ports:
      - "80:80"
    env_file:
      - frontend/.env
 
  
