version: "3"

services:
  backend:
    build: backend
    image: face-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - backend/.env_backend
    networks:
      - backend
  
  frontend:
    build: frontend
    image: face-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
  
