version: "3.9"

services:
  backend:
    build: backend
    image: face-backend:latest
    ports:
      - "8080:8080"
    env_file:
      - backend/.env_backend
  
  frontend:
    build: frontend
    image: face-frontend:latest
    ports:
      - "5000:5000"
    env_file:
      - frontend/.env
  
